brew "ripgrep"
brew "mas"
brew "fish"
brew "rclone"
brew "jq"
brew "ffmpeg-full"
brew "btop"
brew "lua"
brew "mpv"
brew "openjdk@17"
brew "unar"
brew "tree"

cask "kitty"
cask "brave-browser"
cask "discord"
cask "heroic"
cask "hammerspoon"
cask "raycast"
cask "visual-studio-code"
cask "stats"
cask "obs"
cask "middleclick"
cask "quickrecorder"
cask "font-hack-nerd-font"
cask "vlc"

mas "LINE", id: 539883307
